### ISSUE TITLE
Replace the setup section in README.md

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/chat-backend#120]
We manage dependencies with poetry in `skywardai/container` repo now. So, it does not include any of the tools, like pre-commit, pytest. These tools should be online in development environment. So, we need to add a way to support installing these tools. Something like developtools.txt

**Comment by CarterFaceySmith** [comment]
@Aisuko I'll tackle this one next, as far as the actual implementation is a simple requirements.txt type setup sufficient? I.e. review requisite tools for development environments, collate into requirements.txt and merge in? Or am I reading this wrong?

**Comment by Aisuko** [comment]
Hi @CarterFaceySmith, You are right. we should add below to the requirements.txt:

```
pre-commit==3.7.0
pytest==8.1.1
```

Please put the requirements.txt inside `backend` folder

**Comment by CarterFaceySmith** [comment]
PR merged in, issue seems ok to close @Aisuko?

**Comment by Aisuko** [comment]
@CarterFaceySmith thank you
