### ISSUE TITLE
[feature] Evaluate accuracy rate.

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/chat-backend#125]
Currently, we do not have too many ways to evaluate the accuracy of RAG response. So, we need to implement an evaluation framework to help us to do this.

Reference:
* https://www.kaggle.com/code/aisuko/arena-leaderboard-with-semscore
* https://www.kaggle.com/code/aisuko/evaluating-llms-on-any-dataset-using-semscore

**Comment by CarterFaceySmith** [comment]
@Aisuko Happy to take this issue, were the team set on using sem score as a measure of accuracy?

**Comment by Aisuko** [comment]
Hi @CarterFaceySmith good to see you want to put effort on this issue. However, we need to fix the issue we hit on Kaggle first. I suggest you do some issues with `good-first-issue`. Those issues are easier for you to do contributions.

**Comment by Aisuko** [comment]
Hi @CarterFaceySmith I have been set `CUDA_LAUNCH_BLOCKING` to 1 then the notebook does not work anymore. The whole notebook kernel is down(no idea why it happened). And I discussed to the author, he suggests to run the notebook on a single 3090 GPU. https://medium.com/@aisuko/thanks-for-your-great-work-0becf405a720

I have some GPU resource at RMIT Race Hub. If you want to test it. ping me anytime.

For the Huggingface token, I suggest you create a token in your HuggingFace account. You can update fine-tine model  to your own huggingFace
