### ISSUE TITLE
 [feature] Standardlize log system

### ISSUE THREAD

**Issue by Micost** [SkywardAI/chat-backend#130]
Use loguru as log lib for all loggings,  avoid using print or other type of the logging systems

**Comment by CarterFaceySmith** [comment]
Added to recent PR.

**Comment by Aisuko** [comment]
Hi @CarterFaceySmith  thank you. Feel free to take the issue. Hi, @Micost please give more detail of the logger system that you want to implement.

**Comment by Micost** [comment]
This issue is fixed along with requirement.txt in PR#134,  PR reviewed

**Comment by CarterFaceySmith** [comment]
Fixed with PR #134.
