### ISSUE TITLE
[Feature]: Login and register API 

### ISSUE THREAD

**Issue by Micost** [SkywardAI/chat-backend#139]
### What feature are you requesting?

This is a sub issue of #138 

Login and register API ,  simple one should work , no need to change the data structure of current account , there are already user management API in backend , update them to support anonymous user

**Comment by cbh778899** [comment]
The route /api/auth/signin asks both username and email to login, which in most applications there's only one field called account..Is it really necessary?

**Comment by Micost** [comment]
> The route /api/auth/signin asks both username and email to login, which in most applications there's only one field called account..Is it really necessary?

Forget the email in login,  it's totally not necessary and I'm going to remove email in login
