### ISSUE TITLE
[Feature]: Re-ranking the result

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/chat-backend#145]
### What feature are you requesting?

Currently, we get the limited result from the vector db. As we discussed, if we want to increase the accuracy. We want to import re-ranking mechanism. After we get list of results, we should re-ranking the list and pick up the most valuable answer.

**Comment by Micost** [comment]
This feature was added in PR #151， currently we use RAG to find 5 results and then rerank them by using cross-encoders
