### ISSUE TITLE
[DOC]: The README setup step should be shown more obviously for developers

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/chat-backend#15]
We want the quick setup has the same big font size with regular setup.

<img width="913" alt="Screenshot 2024-03-20 at 10 28 56 PM" src="https://github.com/SkywardAI/chat-backend/assets/8053949/a45f47d2-3089-4f19-b2f0-43130cd0e190">

**Comment by ise8933** [comment]
Hello! Can I help contribute to this?

**Comment by Aisuko** [comment]
Yes, for sure.

**Comment by Aisuko** [comment]
Close by a5783a9920968083ba56c60968cafda9505d9831
