### ISSUE TITLE
[Feature]:  Adapting pipeline to our base line language model

### ISSUE THREAD

**Issue by Micost** [SkywardAI/chat-backend#153]
### What feature are you requesting?

Model https://huggingface.co/apple/OpenELM-270M-Instruct was introduced as small , high performance and flexible with multiple purpose of usage.  

Also try Microsoft/ph1-1_5，  choose one of the model as default model 

Test and apply this model in encoder ,  conversation pipeline and summarization pipeline in backend

**Comment by Aisuko** [comment]
As we discussed, OpenELM with a "Apple" license. It isn't our option now. Please check the in the [discussion](https://github.com/orgs/SkywardAI/discussions/14)
