### ISSUE TITLE
[Feature]: Dataset for test 

### ISSUE THREAD

**Issue by Micost** [SkywardAI/chat-backend#155]
### What feature are you requesting?

Prepare dataset for test purpose

**Comment by Aisuko** [comment]
https://www.kaggle.com/code/aisuko/transform-dataset-to-embeddings

**Comment by Aisuko** [comment]
@Micost @jinronga

Please check the dataset format in here
https://huggingface.co/datasets/aisuko/RMIT-2024-pd-study-areas?row=0

The notebook in here https://www.kaggle.com/code/aisuko/pre-processed-rmit-pd-study-areas

**Comment by Micost** [comment]
@Aisuko @jinronga yes, I think the above dataset works.   We can load this dataset once #154 completed

**Comment by jinronga** [comment]
ok

**Comment by Aisuko** [comment]
Thanks for you guys support
