### ISSUE TITLE
[DOC]: The icons should be reformat

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/chat-backend#16]
1. The icons should be on the same row
2. The icon which doesn't work should be fixed and remove.

<img width="844" alt="Screenshot 2024-03-20 at 10 30 41 PM" src="https://github.com/SkywardAI/chat-backend/assets/8053949/8c467231-8370-47e7-b172-31063f8dcb8c">

**Comment by Janak04** [comment]
I have removed all icons except for the backend CI/CD and the release drafter, is that ok?

**Comment by Aisuko** [comment]
Hi @Janak04 yes, you are right. We can also keep "pre-commit" icon in README.md.
