### ISSUE TITLE
[bug]: tickets list is empty.

### ISSUE THREAD

**Issue by Wen-ace** [SkywardAI/chat-backend#23]
<img width="1464" alt="image" src="https://github.com/SkywardAI/chat-backend/assets/24608711/6aa96fe6-cd9f-40eb-a2b6-7a541c1c70c1">

**Comment by Micost** [comment]
[feat:v0.1 fix chat](https://github.com/SkywardAI/chat-backend/commit/75e6b475536899b1b0cd5056d9f92055e5c51a8c)
