### ISSUE TITLE
[feature] Add issue template

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/chat-backend#35]

**Comment by CarterFaceySmith** [comment]
@Aisuko It seems the RMIT group cannot access the repo settings menu for setting up of templates re this issue.

**Comment by Aisuko** [comment]
Hi @CarterFaceySmith Please follow this instruction https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

We want to add a configuration file for the issue template, no special request.
