### ISSUE TITLE
[feature] Add Security.md

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/chat-backend#36]

**Comment by CarterFaceySmith** [comment]
@Aisuko Were there specific requirements regarding information to be covered for this document or was it to be tailored more towards generic security info relating to the tech stack?

**Comment by Aisuko** [comment]
Hi @CarterFaceySmith, we only want to have a simple Security.md file like https://docs.github.com/en/enterprise-server@3.8/code-security/getting-started/adding-a-security-policy-to-your-repository. There is no further request.
