### ISSUE TITLE
Launching containers using Docker Compose on Windows system may result in: backend_app        | exec /usr/backend/entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by jinronga** [SkywardAI/chat-backend#56]
During the Windows build startup, the error '| exec /usr/backend/entrypoint.sh: no such file or directory' occurs, causing the entrypoint.sh script to be unable to execute.
Execution failed!
The same issue occurs on my computer, company computers, and my colleagues' computers. How can we resolve this?

![微信图片_20240327210136](https://github.com/SkywardAI/chat-backend/assets/52482860/89e2788a-8424-4f97-be00-41910329cbef)
<img width="1010" alt="微信图片_20240327210227" src="https://github.com/SkywardAI/chat-backend/assets/52482860/e4880f0a-eec6-4567-9226-dd254b6c1c8f">

**Comment by jinronga** [comment]
I think all Windows users will encounter this problem. （Docker version 25.0.3）

**Comment by Aisuko** [comment]
I saw your log of docker daemon. It means you docker cannot create container successfully. @Micost uses Windows platform. However, he uses WSL2(unix like environment). So, Maybe we can discuss this in next meeting.

**Comment by Aisuko** [comment]
@arvin936 is working on these kind of issues. I believe we should remove `chmod +x entry_point.sh` in Dockerfile.

**Comment by arvin936** [comment]
> @arvin936 is working on these kind of issues. I believe we should remove `chmod +x entry_point.sh` in Dockerfile.

I think the key to the problem is not to perform the build process on Windows, we should perform these steps during the release of the image. For newcomers who are still trying to run the program, the build process should not be their current focus.
