### ISSUE TITLE
The final product of release should be a directly runnable image, not just a source code package.

### ISSUE THREAD

**Issue by arvin936** [SkywardAI/chat-backend#58]
The final product of release should be a directly runnable image, not just a source code package.
The build process can be a place for interested people to explore, but it should not be a requirement to run the program.
After this change, docker-compose can be run directly without a build process. Every time a new version is released, push the latest image to the mirror warehouse, and point the latest tag to the latest version number image, the latest image used on docker-compose.

**Comment by Aisuko** [comment]
I think we can create a new docker-compose for only demo usage.
