### ISSUE TITLE
It is recommended that the environment variables set in the current make env step be sunk into the image.

### ISSUE THREAD

**Issue by arvin936** [SkywardAI/chat-backend#59]
It is recommended that the environment variables set in the current make env step be sunk into the image.
Judging from the content of the make env step, these environment variables do not change as the user environment changes. We can set these variables in the final released image to reduce the steps required for users to run.

**Comment by Aisuko** [comment]
As we discussed, we want to be more flexible. So, we can leave the environment variables in docker-compose.yaml. It is be easier for deployment with different middleware, like miniio, vector db.
