### ISSUE TITLE
Image should be Python-slim

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/chat-backend#60]

**Comment by arvin936** [comment]
Which version of python should we use？

**Comment by Aisuko** [comment]
hi @arvin936, I am prefer python 3.11.8-slim

https://hub.docker.com/layers/library/python/3.11.8-slim/images/sha256-346e2b922dbd8f853cd1a63f142290fc7449b0a59b0e2b600ef7dc98ca5ab436?context=explore
