### ISSUE TITLE
[feature]: Support load more dataset with different formats

### ISSUE THREAD

**Issue by Aisuko** [SkywardAI/chat-backend#95]
Now we support load .csv from the page. Here are some considerations:

* .csv is good and convenience. However, we should restrict the format of the content of CSV.

However, if we support some internal dataset from our community it is also good feature. For example, I'm a student of RMIT. And I load pre-processed RMIT student policy from our dataset centre. And all the questions context will be related to RMIT.

And we are planing support two datasets from a drop lists at the frontend page. Two sections should on the page  like below:

**Comment by Micost** [comment]
Apis are defined in PR#98  One new api(file/dataset) to list recent used dataset . One api (train) added new param dataset to processs dataset as the second data format.
